Added Changelog file
rehlds/metamod-r pull request #73
Opened 2024-10-28 09:34 UTC by stamepicmorg

* Resolves https://github.com/rehlds/.github/issues/13 for `metamod-p` repo.

2024-10-28 12:50 UTC, a1batross commented on CHANGELOG.md
> +- Started `metamod-r` project by forkig from `metamod-p`. Based on version `1.20p35`.
forkig

2024-10-28 12:51 UTC, a1batross commented on CHANGELOG.md
> +- Updateed `C++ Intel Compiler` version `17.0` > `19.0`.
Updateed

2024-10-28 16:06 UTC, wopox1337 requested changes
Overall, I like the new format, which is in line with https://keepachangelog.com specs. 

Thank you!

2024-10-30 10:41 UTC, wopox1337 approved these changes

2024-10-30 11:44 UTC, merged